### ISSUE TITLE
Issues compiling XRT on Debian 10 

### ISSUE THREAD

**Issue by Redoxon33** [ikwzm/ZynqMP-FPGA-XRT#2]
Hello,

I am a master's student working on my Master's Thesis, and I am experiencing several issues while trying to compile the XRT library on a Debian 10 environment on a Zynq Ultraescale + XU8 Mercury. I would like to ask for your assistance with some specific errors I've encountered.

When attempting to compile using` ./build.sh ` from the XRT repository, I receive an error indicating that `hw_emu cannot be found.`
When trying `./build_edge_deb.sh` with `-dist buster/focal --arch arm64,` I encounter issues with` chroot.`
Despite these problems, I have been able to make significant progress thanks to your repository. However, I have reached a point where I need to install linux-headers, but my research group at the university does not allow me to install them.

I understand if this is not the appropriate place to raise these issues, and if so, I will close the issue. However, I believe your expertise and knowledge could be very helpful in resolving these problems.

Of course, I will include your repository in my thesis and give you proper credit.

Thank you in advance for your time and assistance.

**Comment by ikwzm** [comment]
Thanks for the issue.

XRT (Xilinx Run Time) is divided into two parts: a library that runs in user space and a Linux Kernel Module that runs in Linux Kernel space.
In the case of Debian/Ubuntu, the Linux Kernel Module part uses a mechanism called DKMS (Dynamic Kernel Module Support).
DKMS automatically builds the Linux Kernel Module from source code when the Linux Kernel of the target system is updated to a newer version. Therefore, a set of header files of the target Linux Kernel is required to operate DKMS.

If there is no Linux header group, the Linux Kernel Module must be incorporated by another method.
For example, you can embed the Linux Kernel Module in the Linux Kernel beforehand, or you can prepare a pre-built Linux Kernel Module and embed it by using insmod.

If it is possible to incorporate the Linux Kernel Module without using DKMS, please omit building the xrt-zocl-dkms package when building XRT.

**Comment by Redoxon33** [comment]
Thanks for addressing the issue. I will give it a try, and if I get to the end, I'll let you know.
